import test from 'node:test';import assert from 'node:assert/strict';
import {createProblemState,updateProblemState,compactProblemState} from '../core/resolution/problem-state.js';
import {assessAnswerability} from '../core/answerability/answerability-engine.js';
import {prepareVisualTeacherPackage} from '../core/privacy/visual-teacher-package.js';
import {orchestrate} from '../core/orchestration/unified-orchestrator.js';

test('problem state keeps attempts and does not lose the active target',()=>{let s=createProblemState({target:{id:'r1',label:'router'}});s=updateProblemState(s,{problemSession:{attempts:[{text:'已经重启过'}],symptoms:[{text:'红灯闪'}],evidence:[],goal:'restore_network'}});const c=compactProblemState(s);assert.equal(c.target.id,'r1');assert.equal(c.attemptedActions.length,1)});
test('answerability asks for clarification when target is not grounded',()=>{const a=assessAnswerability({observation:{confidence:{overall:.8}},problem:{intentHypotheses:[{intent:'troubleshoot'}],referencedObjects:[],unknownFacts:[]},capabilities:{searchAvailable:true}});assert.equal(a.decision,'CLARIFY')});
test('freshness cannot be answered locally from memory',()=>{const a=assessAnswerability({observation:{confidence:{overall:.9}},problem:{knownFacts:[{id:'x'}]},problemState:{facts:[{id:'x'}],target:{id:'r1'},unknowns:[]},retrievalPlan:{needsFreshness:true},capabilities:{searchAvailable:true}});assert.equal(a.decision,'SEARCH')});
test('visual teacher package requires consent before sending image',()=>{const taskPackage={conversation:[],observations:[],evidence:[]};const media=[{type:'image',role:'roi',dataUrl:'data:image/jpeg;base64,xx'}];const blocked=prepareVisualTeacherPackage({taskPackage,answerability:{decision:'TEACHER'},media,policy:{requireExplicitImageConsent:true},consent:false});assert.equal(blocked.allowed,false);const ok=prepareVisualTeacherPackage({taskPackage,answerability:{decision:'TEACHER'},media,policy:{requireExplicitImageConsent:true},consent:true});assert.equal(ok.allowed,true);assert.equal(ok.package.media.length,1)});
test('unified orchestrator remains final authority over advisory answerability',()=>{const context={understanding:{answerability:{decision:'HUMAN'}},safety:{risk:{}},evidence:{resolution:{},request:{},analysis:{},consensus:{}},retrieval:{plan:{},packageSearch:{}},planning:{intentPlan:{}},external:{teacherCount:2,searchAvailable:true,plannerAvailable:true},task:{},verification:null};const r=orchestrate({context});assert.equal(r.route,'HUMAN')});
