import test from 'node:test';import assert from 'node:assert/strict';
import {planSpecialistCapabilities} from '../core/orchestration/specialist-capability-plan.js';
import {routeIntelligenceGap} from '../core/orchestration/intelligence-gap-router.js';

const provider=(id,caps,extra={})=>({id,getProfile(){return {capabilities:caps.map(capability=>({capability,score:1})),privacyModes:['cloud'],latencyClass:'medium',costClass:'medium',reliabilityScore:.8,evidenceScore:.8,historicalSuccess:.7,...extra}},async healthCheck(){return {status:'ready'}}});

test('plans capabilities rather than naming AI brands',()=>{const p=planSpecialistCapabilities({task:{type:'current_price'},freshness:{required:true}});assert.equal(p.providerNeutral,true);assert.equal(p.principle,'SELECT_CAPABILITY_NOT_BRAND');assert.ok(p.requiredCapabilities.includes('current_retail_data'));assert.ok(!JSON.stringify(p).match(/openai|google|claude|gemini/i));});
test('current price selects current-data specialist over generic frontier reasoning',async()=>{const plan=planSpecialistCapabilities({task:{type:'current_price'}});const routed=await routeIntelligenceGap({gap:plan,providers:[provider('generic',['frontier_reasoning']),provider('retail',['current_retail_data','current_web_search'])]});assert.equal(routed.chain.length,1);assert.equal(routed.selected.provider.id,'retail');});
test('visual residual requires visual specialist and can request image input',()=>{const p=planSpecialistCapabilities({task:{type:'identify',requiresImages:true},residual:{type:'visual identity',requiresImage:true}});assert.ok(p.requiredCapabilities.includes('visual_reasoning'));assert.ok(p.requiredCapabilities.includes('vision_input'));});
test('learned task success can outrank static provider preference',async()=>{const plan={kind:'deep_reasoning',requiredCapabilities:['frontier_reasoning']};const a=provider('a',['frontier_reasoning'],{historicalSuccess:.9,reliabilityScore:.9});const b=provider('b',['frontier_reasoning'],{historicalSuccess:.5,reliabilityScore:.7});const store={get(id){return {attempts:20,historicalSuccess:id==='b'?.99:.2,avgLatencyMs:1800}}};const routed=await routeIntelligenceGap({gap:plan,providers:[a,b],performanceStore:store});assert.equal(routed.selected.provider.id,'b');});
