import test from 'node:test';import assert from 'node:assert/strict';
import {createTeacherOutcomeStore} from '../core/orchestration/intelligence-gap-router.js';
import {routeIntelligenceGap} from '../core/orchestration/intelligence-gap-router.js';
import {applySpecialistExploration} from '../core/orchestration/specialist-exploration-policy.js';
const provider=(id,health='ready')=>({id,getProfile(){return {capabilities:[{capability:'visual_reasoning',score:1}],privacyModes:['cloud'],latencyClass:'medium',costClass:'medium',reliabilityScore:.8,evidenceScore:.8,historicalSuccess:.7}},async healthCheck(){return {status:health}}});
const plan={kind:'visual_residual',requiredCapabilities:['visual_reasoning']};

test('one lucky verified result is shrunk and cannot masquerade as proven 100 percent',()=>{const s=createTeacherOutcomeStore();s.record({providerId:'new',capabilities:['visual_reasoning'],taskKind:'visual_residual',signal:'verified_success'});const x=s.get('new','visual_residual',['visual_reasoning']);assert.ok(x.rawHistoricalSuccess>.9);assert.ok(x.historicalSuccess<.9);assert.ok(x.confidence<.5);});
test('bounded exploration can give an uncertain eligible provider a chance without changing capability gates',()=>{const ranked=[{provider:{id:'proven'},score:.9,learned:{evidenceWeight:20}},{provider:{id:'new'},score:.82,learned:{evidenceWeight:0}}];let found=false;for(let i=0;i<500;i++){const x=applySpecialistExploration(ranked,{explorationRate:.2,requestKey:`r${i}`});if(x.explored){found=true;assert.equal(x.selected.provider.id,'new');break}}assert.equal(found,true);});
test('unhealthy provider is excluded before failover chain is built',async()=>{const routed=await routeIntelligenceGap({gap:plan,providers:[provider('dead','down'),provider('a'),provider('b')]});assert.deepEqual(routed.chain.map(x=>x.provider.id).sort(),['a','b']);assert.deepEqual(routed.chain.map(x=>x.failoverRank),[1,2]);});
test('proven provider remains default when exploration is disabled',async()=>{const s=createTeacherOutcomeStore();for(let i=0;i<8;i++)s.record({providerId:'a',capabilities:['visual_reasoning'],taskKind:'visual_residual',signal:'verified_success'});const routed=await routeIntelligenceGap({gap:plan,providers:[provider('a'),provider('b')],outcomeStore:s});const x=applySpecialistExploration(routed.chain,{enabled:false});assert.equal(x.selected.provider.id,'a');assert.equal(x.mode,'exploit');});
