import test from 'node:test';import assert from 'node:assert/strict';
import {createTeacherOutcomeStore,learnTeacherOutcome} from '../core/orchestration/intelligence-gap-router.js';
import {classifySpecialistOutcome} from '../core/orchestration/specialist-outcome-learning.js';
import {routeIntelligenceGap} from '../core/orchestration/intelligence-gap-router.js';
const provider=(id)=>({id,getProfile(){return {capabilities:[{capability:'visual_reasoning',score:1}],privacyModes:['cloud'],latencyClass:'medium',costClass:'medium',reliabilityScore:.8,evidenceScore:.8,historicalSuccess:.7}},async healthCheck(){return {status:'ready'}}});

test('technical API success alone is not learned as factual success',()=>{const s=createTeacherOutcomeStore();s.record({providerId:'x',capabilities:['visual_reasoning'],taskKind:'visual_residual',signal:'technical_success_only'});const x=s.get('x','visual_residual',['visual_reasoning']);assert.equal(x.historicalSuccess,.5);assert.equal(x.rows[0].verifiedSuccesses,0);});
test('authoritative contradiction strongly weakens provider capability outcome',()=>{const s=createTeacherOutcomeStore();for(let i=0;i<3;i++)s.record({providerId:'x',capabilities:['visual_reasoning'],taskKind:'visual_residual',signal:'verified_success'});s.record({providerId:'x',capabilities:['visual_reasoning'],taskKind:'visual_residual',signal:'authoritative_contradiction'});const x=s.get('x','visual_residual',['visual_reasoning']);assert.ok(x.historicalSuccess<.8);assert.equal(x.rows[0].contradictions,1);});
test('outcome classifier separates verified, corrected and unresolved results',()=>{assert.equal(classifySpecialistOutcome({technicalOk:true,verified:true}),'verified_success');assert.equal(classifySpecialistOutcome({technicalOk:true,userCorrected:true}),'user_corrected');assert.equal(classifySpecialistOutcome({technicalOk:true,residualResolved:false}),'residual_unresolved');});
test('capability-specific verified outcomes can change specialist ranking without brand lock-in',async()=>{const s=createTeacherOutcomeStore();for(let i=0;i<6;i++){s.record({providerId:'b',capabilities:['visual_reasoning'],taskKind:'visual_residual',signal:'verified_success'});s.record({providerId:'a',capabilities:['visual_reasoning'],taskKind:'visual_residual',signal:'user_corrected'});}const routed=await routeIntelligenceGap({gap:{kind:'visual_residual',requiredCapabilities:['visual_reasoning']},providers:[provider('a'),provider('b')],outcomeStore:s});assert.equal(routed.selected.provider.id,'b');});
